### ISSUE TITLE
How do I install Parpar on Linux via terminal without Root / Sudo access ?

### ISSUE THREAD

**Issue by MrHGill** [animetosho/ParPar#27]
I would like to install Parpar on my shared seedbox, please help

**Comment by animetosho** [comment]
Depends what's already available there. If Node.js, NPM and compilers are there, just install it [normally](https://github.com/animetosho/ParPar#install-via-npm) but without the global (`-g`) flag.

Otherwise, install it on a machine you do have root on and copy everything across. Make sure you're using the same Node.js version, and you may have to [remove the `-march=native` compile flag](https://github.com/animetosho/ParPar#native-binary-targeting).
