### ISSUE TITLE
[Request] Make the program check itself.

### ISSUE THREAD

**Issue by uxmy** [animetosho/ParPar#38]
I wish you can add an auto checksum verification to the program (similar to the one implemented in **par2j** ), to make sure the executable is not damaged by bit rot for example.

**Comment by animetosho** [comment]
Thanks for the suggestion!

This is an interesting idea, probably a bit tricky to implement though (has to be tied to a build). There's also the question of dependencies, which can't be verified by ParPar, but I suppose there may be other ways to do it.

I can't see it implemented in par2j though? Just tried modifying a byte in the executable, and it runs without complaint. Or are you referring to some other check perhaps?

**Comment by animetosho** [comment]
Ah I see, missed that - thanks for pointing that out!

It looks like there's some post-build step (alter executable's CRC) that the author performs before release, because building par2j from source causes that error.

I can look at adding a check for built executables, but don't think there's a nice way to do it for NPM based installs.
